kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-root-ca.crt
  namespace: dev-kafka
  uid: f985a4f1-65a3-4782-bd03-5fe4f9ea224a
  resourceVersion: '36793183'
  creationTimestamp: '2024-10-28T06:43:45Z'
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the kube-apiserver when using internal endpoints such as the internal service IP or kubernetes.default.svc. No other usage is guaranteed across distributions of Kubernetes clusters.
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2024-10-28T06:43:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:ca.crt': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubernetes.io/description': {}
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIP8B7ZyzpBqAwDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjQwOTA3MDcxNzExWhcNMzQwOTA1MDcxNzExWjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAM7Q+sMh+o+9T4K7/8dgK+wQneEeVH2/
    +3eGWpSSDbgAJG0VhJJH08t0dnxiKBuyUA2dApunFSjEjLWgqZPM07D3q0q7I1O9
    N7WE62ABviY2nmU5C+N/WhZx37aaB46gyk53C2/WvXtjgbn0+K1LUloZxZaiuuIh
    BHZt+JbSCSiotKJVEmSsbaUDeX4t3l4H8dgkfZ7fVbz10zu0r118xaio3pxk3KZy
    geuIQX7fSJle4nSl9tgI4j3NcocwC9Xvc57BPvm+I6W8LFgar055E+0yqp7e7rng
    cqr4IhOhiFkq1l3moBNTg/y3mi73vKad1JAd8x3PAfU4Ad+KCWxOHskCAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFFwm
    4dG4fPl6vQKirfnUOKzBEJqeMA0GCSqGSIb3DQEBCwUAA4IBAQA/zGEjqa79FlNo
    LzPUgY9VLSa7/ezZHkHk/VNxCNeMm6pLfF7+k6QeFREXwmhQ+dFREXGBM3jJV7Ye
    6srmHf/yukb3GCQZko8c6zpj758i3p4nd96peg8Jzexj8ZLMmLmA6IUVd8aBbnyE
    gCcwZLCe/BIlS5LVjrmwgk/6o+BUw+qmpSxumlJzeli1uStFE5VfOP6YPIodfiM3
    dCD3qPulQSL2nBVBHxXHNc5FLMnVGsId1UcGJyKkdTS33zwHnW1HjwxvT/QV2ny0
    XNwsxloZ9aAekRjO0LXkq5gHgCY/vxv1OXKP2tvd321cddjhwEkHROwQm07PxS+x
    RgH55TsP
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIIAojtDDEfqxgwDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTI0MDkwNzA3MTcxMVoXDTM0MDkwNTA3MTcxMVowPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8vTz2jaqNyRW
    kgY05ruggFt/DEgMlCU0riIDKCXfoKGBzLN2jq9H/g8Tt063xK8DnbROo4dwByq0
    ZJRH1tr5nYskn6Ti7THqsh2kkCzh2nZLelfNgdVV/CZND3OQgx+9/1JIRw6eLsnq
    pjBri5R1NlycS8LOf/TvoXtSPXOP27TY1ub2wbYtevU1Xgk8oV0KQScvOxntUBgp
    ZKOy/1QQF4Kgydj+mad5p7KOH2U1+McGxs0laHCRep6nfI+ZWuICGSoRpnSVyN7E
    gMtgWrLS0aAToEFjVsHTXFBzR+YrFDWIStpDeHRzGqMt5bkrFo113EKxLNpnXZHz
    EWtouhvAzwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUKj9VmXhW36zLWDut4nlNcx13bEMwDQYJKoZIhvcNAQELBQAD
    ggEBACrbLL8H4roXuEHPrFZ3m1DqEcrNIkSL2IvQBNiWAXULOxln/uPmqohiJ1Ij
    1H77yjkflHOat+qG4YQv610tatVnlByn0kyB5tLwuyjx9n+Gx9R03mLeKQ59kkns
    H+RdDjzTO4HfDw/1/izJIimV9jJGcu3e5Ql/GWD3+VxyycCOrmN6wko2lpbukIZk
    Kw5tWPYXeYUuF4v73aqvzEYZY1vtSlzAuCjKTMi05gVU4vGYgkq+0ItKzXrbPg2Y
    1bCN7XBvkWBrlT8dMKeW2SA8IslJuMrOPp7fyddB1jn6yKRvtSvMWz3IQwt6K/II
    JcIZLukjoTgLgLearE6zlrz5/v0=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIIQ395PTZvbAMwDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTI0MDkwNzA3MTcxMVoXDTM0MDkwNTA3MTcxMVowRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEArbyJxkNfjVhj7+KfR25ujJb4uD9mmpWy56g80ofPIIXZAqOVcFPNQr5L9a+w
    JjZlr3WdBsesSHbu5h8kAe9yd2kNPCYlJCtBnR2F2j8jz5hylO0weJnyO+JntLQk
    nJgsv9SGdpAisgPT/QmWwazGkxjH5yyw0aNGuEOk5NubjVPx+So9KIKN6jx0sv4Q
    iEDs1nX0BI317pgh1Yh/40Qt7LcUrs0gAuWzltZ/WDhUPyPxRSQdCzgv80QzlH2B
    qME+PP1vbQuuCbARLJ8VQeSKg+dfkyAbEIr2O0JO/9XzS4zH/DfmV9Q1xL1weoIL
    sEtCRlfP31ZwtbAJq0b6Bqs05wIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUkXeTFElw5cEgaX91d08QWarO3O8wDQYJ
    KoZIhvcNAQELBQADggEBAKMMDBSXjSMzfWdMFPd+4TAsCYdgMpO2SITd52jG/039
    vmFnNh+DMAKavJLnaCV9tSv9s2D6l9ZU3L2AEyS1WE13Gy7HdfOWNDG+FN6F2DSQ
    9tAMKGXEYDYperiy1GG6cVfkySJGZq5FoeAEiZ3bUDDqQsDyzwdM6owOcvUGfrnQ
    h0ReLsU8ZGlBflX9posExPbecnxYYOBA19HF5rPLzTywU2hYrI10cTwHBDFOTMHZ
    66msAewDJQJMB1a8pGiYyln9hbJZpdQOex/9pA2aZEKEQOHLd2SjXS163jS/TAS6
    8XrEsEQowokkxTOgiUuTSqxlbr1ptmAPCMmGISSBS40=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIHI++trM0GLgwDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNzI1Njk0NjgyMB4XDTI0MDkwNzA3Mzgw
    MVoXDTM0MDkwNTA3MzgwMlowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNzI1Njk0NjgyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzMt9
    IJYsyghqj0452ifnyQDoZKBXgoMBF8E7nVancdZWthN0myiSvF6zyKKd50F/pAW5
    vR0WB/rTbPBssIEc3CTl7NiF2CanJJJOxELRryeyTeo7hp9CNOX+YK5ZHDCCnilE
    DTqTmo/+FmknT35CN6ks//AsxVOvXZ9iTvmm9BOpYuflruFQ8Ic7P3JM2CELXq3j
    /8EbQlPwier/pWcWwvJK2vhOwatJc5AZC7Ah0Uym1V8jodfrfSpgOVbzEf/PVMRL
    lop2wQ1IgGUriJgYVaDQKiBTScksuOvsmeWwp0kUcf4v6S7kCI3eGK3ogIaI+rIh
    XXbWdKCeYPoywbTOmQIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQUYafKgG9CqcbWYnD6Z1fjIK9zuv0wHwYDVR0jBBgw
    FoAUYafKgG9CqcbWYnD6Z1fjIK9zuv0wDQYJKoZIhvcNAQELBQADggEBAL4aSyme
    GyimSKBdutSNs1G7AD4nwMp7unPnN9+uqUxzuXaVM1Fx90ww9173D4GaSjs4JCim
    WQ2lLQJkz1ovZn68VCcNUG1ZrXCjUgvsMLjqvjJN5+aVT51Y1czezUMSqhVT7Ffd
    cVMxu35Z4X1YiNK/6vEwLjfu+GZRMp9q7GE1A6y1ahfVCeNowQoqwaJFsmvLxzG2
    G+tm4nbb34+qD2hpePHBTPgo0I9YzsJ0dbqlENMu7svzR07KrFVbbH1hre+mMBji
    vTlMEAiVsKebAK2Kp5wb1fQXTlg93QO2jpAjiRxUMD+Xn4eRwX/KBYqoq9KYymM5
    oQvuqvGhd72He/4=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFvDCCBKSgAwIBAgITGgAViRBWvEl9KTVrsgAAABWJEDANBgkqhkiG9w0BAQsF
    ADBAMRMwEQYKCZImiZPyLGQBGRYDU0JJMRIwEAYKCZImiZPyLGQBGRYCQUQxFTAT
    BgNVBAMTDFNCSS1QUk9ELVJDQTAeFw0yNDA4MDkwOTQ4MjlaFw0yNjA4MDkwOTQ4
    MjlaMHwxCzAJBgNVBAYTAklOMQswCQYDVQQIEwJNSDEMMAoGA1UEBxMDTVVNMQww
    CgYDVQQKEwNTQkkxCzAJBgNVBAsTAklUMTcwNQYDVQQDEy5jb25zb2xlLW9wZW5z
    aGlmdC1jb25zb2xlLmFwcHMuZGV2LnNiaWVwYXkuc2JpMIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEA6cAX8rQloBQWg61/lGSgN5W0CxM7bjb6GIN+3tlR
    2du4ia2+JHD6joF+UipZCCAzXFUKOMrLAzjDHs0m0F6haPioy/FeNsPCm2HSC9Ad
    Wg1ox1veBu/XLa/wK6i6VR2yeRX+ftrikRyQ7xh9nso1kdsQYaT5K/JFZtXFXYFp
    64GN37G6BN/aePAJsfI34PFP5g0+U2/C5kvK96deg5h2Gu2eOs8TXGSMdCvIhQXf
    7EfKUctC9eJ6MjLjOaaTSxuMccePBQi8YiyFyRXtseDLvOCe5ceoarB56VyIgZpS
    fMFqBY0eZ3vcOEUUYXTrEsSRuyTRL8Ku/ZcabaHAI64ynwIDAQABo4ICcTCCAm0w
    IQYDVR0RBBowGIIWKi5hcHBzLmRldi5zYmllcGF5LnNiaTAdBgNVHQ4EFgQU93gk
    ZEw+aZ1IkyuTLU/KTpPnZzUwHwYDVR0jBBgwFoAUN5ogdDBeJP0f5b+u/wD0axV1
    n7AwgcsGA1UdHwSBwzCBwDCBvaCBuqCBt4aBtGxkYXA6Ly8vQ049U0JJLVBST0Qt
    UkNBLENOPVNCSVJPT1RDQVBST0QsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNl
    cnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9QUQsREM9U0JJ
    P2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxE
    aXN0cmlidXRpb25Qb2ludDCBuQYIKwYBBQUHAQEEgawwgakwgaYGCCsGAQUFBzAC
    hoGZbGRhcDovLy9DTj1TQkktUFJPRC1SQ0EsQ049QUlBLENOPVB1YmxpYyUyMEtl
    eSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9QUQs
    REM9U0JJP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0
    aW9uQXV0aG9yaXR5MA4GA1UdDwEB/wQEAwIFoDA8BgkrBgEEAYI3FQcELzAtBiUr
    BgEEAYI3FQiGgZxcg8eAW4P1kTeE4IFms+pkaoWwlTeDm4AXAgFlAgEUMBMGA1Ud
    JQQMMAoGCCsGAQUFBwMBMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwEwDQYJ
    KoZIhvcNAQELBQADggEBAJ6qek4uPvOFasNVqi3Wo4TDfiwggIQLdN2S4R5/d8cR
    xSiG96r1JR28UxrMhHm5bxllF4qBYMJpC0TWCKUiUpOQDOOZzPQDZpYLefiNfvTy
    5NyYHhSbzWVRZy4McUp3WFUInK5fRby2S/DiHKpTrYqfVTKxD8DeeuXMvVyAddLF
    E1vyW1IXMoASSDrOZ5+G5DhHstY5AWdzCD3nckeVU/FGo3K4ITsjTTE/9rostSnX
    aRcH+DaxKtxrEvhh3FJayGzruIHVM6hVBlecq/6Iff+qalxSLyOzM8j7tuab7QE9
    qTqhde1FAztcxwMUwFwOUIiz/wr7uneJN+2PfBKPeK0=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDdTCCAl2gAwIBAgIQTAMTWJxIVapEJZNyGFj6DjANBgkqhkiG9w0BAQsFADBA
    MRMwEQYKCZImiZPyLGQBGRYDU0JJMRIwEAYKCZImiZPyLGQBGRYCQUQxFTATBgNV
    BAMTDFNCSS1QUk9ELVJDQTAgFw0xNzAyMDgwNjU1NDlaGA8yMDU3MDIwODA3MDU0
    N1owQDETMBEGCgmSJomT8ixkARkWA1NCSTESMBAGCgmSJomT8ixkARkWAkFEMRUw
    EwYDVQQDEwxTQkktUFJPRC1SQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDNDSwbN72EKzOcH+xZhOue8ik8kAztotq76DielYz6yZHi9rHavJx3Ic0e
    KTtgr72jHXra3KZG2GgQpvxfLZd/vD+fZRBXQJJJMvcG0gJYKQLXH6nA3AB/g+UI
    Q0ulxGtgajg2ue0SDBWA2b6EEIYf8bf0zaDy2LnyGkyrv02dehwlMhv6RzXIpta/
    JCAWd2l1k70DX6VQTrb1yAh9C0emIBjoC5HcD7nLtid2lyHjNCXyC3ZWQYjO+a0G
    aaGhloJsjyIfazHSi8JPhzldR15kQcxkeLYVF8LiLfs9lmE7IZxcW/NaCpBY6tBV
    nxOsZ3In0x0ZxQgQ2NoZXjjlJPWtAgMBAAGjaTBnMBMGCSsGAQQBgjcUAgQGHgQA
    QwBBMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ3
    miB0MF4k/R/lv67/APRrFXWfsDAQBgkrBgEEAYI3FQEEAwIBADANBgkqhkiG9w0B
    AQsFAAOCAQEAT5jkCD8DR7q73+eiFQrN1gUr8t4I6ShelY1IqbcsBGGmb6fQqN82
    g5QTPLAPT9+6/nv5cAxFZ+nAlE3Xdw3O2ATlf1F/YikXQQ3gGi7aTsKQsQIehPqx
    LLuLPKpavGmY+Wr38Le34Ydw34Fryxqx31xLbkWJohFfcNF0o/asfk4ibGowQNaK
    ZEaW4CORKjEBdyez9l+lfA1N7KLaMx+B2hyU2TgJgzwCf/7Yv/RxB3/E0QyfbehY
    /aTCUqKNgRUnx5njSjZp/LKgNeMQehyfCIGm0rWg0GuD2WrJadrteJOlAH8/tjlI
    yfL49Y51TPqrT+VOXwWlEIrDBvmaAYgIwQ==
    -----END CERTIFICATE-----
